"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group, Mesh, Object3DEventMap } from "three";
import { useFrame } from "@react-three/fiber";
import { BicycleProps } from "./bicycle3d1";

export function Bicycle3d2({
  x,
  y,
  z,
  rotateX = -Math.PI / 2,
  rotateY = 0,
  rotateZ = 0,
  scale = 1,
}: BicycleProps) {
  const meshRef = useRef<Mesh>(null);
  const { nodes, materials } = useGLTF("/3d/bicycle2.glb");

  useFrame((state, delta) => {
    if (!meshRef.current) return;
    meshRef.current.rotation.x -= delta / 6;
  });

  return (
    <mesh
      ref={meshRef}
      castShadow
      receiveShadow
      //@ts-ignore
      geometry={nodes.Object_2.geometry}
      material={materials.main_texture}
      rotation={[rotateX, rotateY, rotateZ]}
      position={[x, y, z]}
      scale={[scale, scale, scale]}
    />
  );
}

useGLTF.preload("/3d/bicycle2.glb");
