"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Grid, useGLTF } from "@react-three/drei";
import { Mesh } from "three";

export function Bicycle() {
  const meshRef = useRef<Mesh>(null);
  const { nodes, materials } = useGLTF("/3d/bicycle1.glb");

  return (
    <mesh
      ref={meshRef}
      castShadow
      receiveShadow
      //@ts-expect-error threeJs 오탐
      geometry={nodes.Object_2.geometry}
      material={materials.main_texture}
      rotation={[-Math.PI / 2, -Math.PI / 20, -Math.PI / 2.5]}
      position={[0, -0.5, 0]}
      scale={2}
    >
      <Grid />
    </mesh>
  );
}

useGLTF.preload("/3d/bicycle1.glb");
