/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

interface Props {
  scale?: number;
  position: [number, number, number];
  rotation: [number, number, number];
}

export function Cloud3({ scale = 1, position, rotation }: Props) {
  const { nodes, materials } = useGLTF("/3d/cloud-3.glb");
  return (
    <group dispose={null}>
      <mesh
        scale={scale}
        castShadow
        receiveShadow
        //@ts-expect-error threeJs 오탐
        geometry={nodes["cloud-3"].geometry}
        material={materials.None}
        position={position}
        rotation={rotation}
      />
    </group>
  );
}

useGLTF.preload("/3d/cloud-3.glb");
